version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - websocket1
      - websocket2
      - my-redis  # Add dependency for Redis

  websocket1:
    build: ./redisbackend
    environment:
      - PORT=8082
      - REDIS_HOST=my-redis
      - REDIS_PORT=6379
    depends_on:
      - my-redis  # Ensure websocket depends on Redis

  websocket2:
    build: ./redisbackend/
    environment:
      - PORT=8082
      - REDIS_HOST=my-redis
      - REDIS_PORT=6379
    depends_on:
      - my-redis  # Ensure websocket depends on Redis

  frontend:
    build: ./frontendws/
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost/ws/

  my-redis:
    image: "redis:latest"
    ports:
      - "6379:6379"  # Expose the default Redis port
