
FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

Copy . .

RUN npm install

RUN npm install -g typescript ts-node

RUN npm run build
 
COPY . .

EXPOSE 8081 8082

CMD ["node", "dist/index.js"]
